# Generated by Django 3.0.2 on 2022-08-15 10:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_1', '0002_auto_20220813_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=50, verbose_name='автор')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='название')),
                ('start_page', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('end_page', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateField(verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
