# Generated by Django 3.0.2 on 2022-08-19 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_auto_20220816_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='author',
            field=models.CharField(max_length=50, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='end_page',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='последняя страница'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='start_page',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='начальная стараница'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_acc',
            field=models.CharField(max_length=50, verbose_name='Telegram'),
        ),
    ]
