# Generated by Django 3.0.2 on 2022-10-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_auto_20220819_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='date_registration',
            field=models.DateField(auto_now=True, verbose_name='registration date'),
        ),
    ]
