# Generated by Django 3.0.2 on 2022-10-27 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_auto_20221027_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='lesson_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time_id',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='SClass',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
